#!/bin/sh

# PIG_LIB=`dirname $0`/../target/scala-2.11/PigCompiler.jar

echo '
 ____  _         _          _____ _ _       _
|  _ \(_) __ _  | |_ ___   |  ___| (_)_ __ | | __
| |_) | |/ _` | | __/ _ \  | |_  | | |  _ \| |/ /
|  __/| | (_| | | || (_) | |  _| | | | | | |   <
|_|   |_|\__, |  \__\___/  |_|   |_|_|_| |_|_|\_\
         |___/
'

if [ -z "$PIG_LIB" ]; then
    echo "Please set PIG_LIB to your PigCompiler jar file"
    exit 1
else
    CP=$PIG_LIB
fi

if [ -z "$FLINK_JAR" ]; then
    echo "Please set FLINK_JAR to your flink-dist jar file (built with scala 2.11)"
	exit 1
else
	CP=$CP:$FLINK_JAR
fi

# the directory to include in classpath to enable backends
# this should actually be set by the user using external variables
if [ -z "$BACKEND_DIR" ]; then # if BACKEND_DIR does not exist, use our default one
    BACKEND_DIR=`dirname $0`/../flinklib/target/scala-2.11/*
    echo "No backend direcory (BACKEND_DIR) specified!"
else
    if [[ "$BACKEND_DIR" == */ ]]; then # if it ends with / it's a directory - include all files using the wildcard *
        BACKEND_DIR=$BACKEND_DIR*
    elif [[ "$BACKEND_DIR" != */\* && "$BACKEND_DIR" != *.jar ]]; then  #if it ends not with /* or .jar we assume it's a dir - append /*
        BACKEND_DIR=$BACKEND_DIR/*
    fi
fi

echo "Including backends in $BACKEND_DIR"

CP=$BACKEND_DIR:$CP:$CLASSPATH

java -Dscala.usejavacp=true -cp $CP dbis.pig.Piglet -b flinks $*
