#!/bin/bash

echo '
 ____  _         ____  _          _ _ 
|  _ \(_) __ _  / ___|| |__   ___| | |
| |_) | |/ _` | \___ \|  _ \ / _ \ | |
|  __/| | (_| |  ___) | | | |  __/ | |
|_|   |_|\__, | |____/|_| |_|\___|_|_|
         |___/                        
'

if [ -z "$PIG_LIB" ]; then
    echo "Please set PIG_LIB to your PigCompiler jar file"
    exit 1
else
    CP=$PIG_LIB
fi

BACKEND=""
while getopts ":b:" opt; do
    case $opt in
        b)
            BACKEND=$OPTARG
            shift
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case $BACKEND in
    "spark")
        if [ -z "$SPARK_JAR" ]; then
            echo "Please set SPARK_JAR to your Spark-assembly-hadoop jar file"
            exit 1
        else
            CP=$SPARK_JAR:$CP
        fi
        ;;
    "flink")
        if [ -z "$FLINK_JAR" ]; then
            echo "Please set FLINK_JAR to your Flink jar file (built with scala 2.11)"
            exit 1
        else
            CP=$FLINK_JAR:$CP
        fi
        ;;
    *)
        echo "Unsupported backend $BACKEND. Please specify your backend via the -b option (spark or flink)."
        exit 1
        ;;
esac

java -Dscala.usejavacp=true -classpath $CP dbis.pig.PigREPL $*
