#!/bin/sh
PIG_LIB=`dirname $0`/../target/scala-2.11/PigCompiler.jar
CP=/Users/kai/Projects/spark-1.3.1/core/target/spark-core_2.11-1.3.1.jar:$PIG_LIB
java -Dscala.usejavacp=true -cp $CP:$PIG_LIB dbis.pig.PigCompiler $*
